task 1

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,5 +1,8 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # 1-install_nginx_web_server: Installs and configures Nginx to return "Hello World!" on the root URL.
+
+# Exit immediately if a command exits with a non-zero status.
+set -e
 
 # Update package lists and install Nginx
 apt-get update
@@ -11,5 +14,3 @@ echo "Hello World!" > /var/www/html/index.html
 # Ensure Nginx is running and configured to start on boot
 # Instead of using systemctl, use the service command
 service nginx start
-service nginx enable
-
